[workspace]
members = ["dlx"]
resolver = "3"

[workspace.package]
authors = ["Ed McCardell <edmccard@hotmail.com>"]
edition = "2024"
repository = "https://github.com/edmccard/dancing-links"
license = "MIT OR Apache-2.0"
